set( CMAKE_CXX_STANDARD 17            )
set( CMAKE_CXX_STANDARD_REQUIRED True )
set( CMAKE_INCLUDE_CURRENT_DIR ON     )

if(NOT WIN32)
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread" )
endif()
